image: jangorecki/r-base-dev
services:
- postgres

variables:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: logrdb
  POSTGRES_USER: logruser
  POSTGRES_PASSWORD: logrpass

before_script:
  - R CMD build . --no-build-vignettes --no-manual # to be removed after gitlab-ci-multi-runner#157

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - R CMD build . --no-build-vignettes --no-manual

test:
  stage: test
  script:
    # dependencies
    - apt-get update -qy
    - apt-get install -y libpq-dev
    - Rscript -e 'install.packages(c("RPostgreSQL","data.table"), repos="https://cran.rstudio.com")'
    # run check
    - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-vignettes --no-build-vignettes --no-manual --as-cran
    # export Rcheck results
    - mkdir rcheck
    - mv $(find . -maxdepth 1 -name "*.Rcheck" -type d) rcheck
  artifacts:
    paths:
      - rcheck

pages:
  stage: deploy
  script:
    # dependencies
    - apt-get update -qy
    - apt-get install -y libpq-dev
    - Rscript -e 'install.packages(c("RPostgreSQL","data.table"), repos="https://cran.rstudio.com")'
    - mkdir public
    # install drat with `packageHtml` function
    - Rscript -e 'install.packages("drat", repos = "https://jangorecki.github.io/drat")'
    # produce drat repo
    - Rscript -e 'drat::insertPackage(list.files(pattern = "*\\.tar\\.gz$"), repodir = "public")'
    # produce html homepage and manual
    - Rscript -e 'drat::packageHtml(repodir = "public", repo.url = "https://jangorecki.github.io/logR", repo.cran = TRUE, manual = TRUE)'
  only:
    - master
  artifacts:
    paths:
      - public
