image: jangorecki/r-base-dev
services:
  - postgres

variables:
  POSTGRES_HOST: postgres
  POSTGRES_DB: logrdb
  POSTGRES_USER: logruser
  POSTGRES_PASSWORD: logrpass
  
before_script:
  - apt-get update -qy
  - apt-get install -y libpq-dev
  - Rscript -e 'install.packages(c("RPostgreSQL","data.table","microbenchmarkCore"), repos=paste0("https://", c("olafmersmann.github.io/drat","cran.rstudio.com")))'

test:
  script:
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
