image: quay.io/jangorecki/r-base-dev
services:
- postgres

variables:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: logrdb
  POSTGRES_USER: logruser
  POSTGRES_PASSWORD: logrpass

pages:
  script:
    # non-R dependencies
    - apt-get update -qq
    - apt-get -qq install -y libpq-dev
    # build pkg
    - R CMD build .
    # install deps
    - Rscript -e 'install.packages(c("RPostgreSQL","data.table"), repos="https://cran.rstudio.com")'
    # install suggests
    - Rscript -e 'install.packages("microbenchmarkCore", repos = "https://olafmersmann.github.io/drat")'
    # run check
    - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-build-vignettes --no-manual --as-cran
    # gl-pages dir and Rcheck results dir
    - mkdir public Rcheck
    # install drat with `insertArtifacts` function
    - Rscript -e 'install.packages("drat", repos = "https://jangorecki.github.io/drat")'
    # produce artifacts
    - Rscript -e 'drat::insertArtifacts(repodir = "public", repo.url = "https://jangorecki.github.io/logR", repo.cran = TRUE)'
    # export Rcheck results
    - mv $(find . -maxdepth 1 -name "*.Rcheck" -type d) Rcheck
  only:
    - master
  artifacts:
    paths:
      - Rcheck
      - public
