variables:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: logrdb
  POSTGRES_USER: logruser
  POSTGRES_PASSWORD: logrpass

pages:
  image: docker.io/jangorecki/r-pkg
  services:
    - postgres
  script:
    # non-R dependencies
    - apt-get update -qq
    - apt-get -qq install -y libpq-dev
    # install deps
    - Rscript -e 'install.packages(c("RPostgreSQL","data.table"), repos="https://cran.rstudio.com")'
    # install suggests
    - Rscript -e 'install.packages("microbenchmarkCore", repos="https://olafmersmann.github.io/drat")'
    # build pkg
    - R CMD build .
    # run check
    - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-manual --as-cran
    # produce artifacts
    - Rscript -e 'drat::insertArtifacts(repo.url="https://jangorecki.gitlab.io/logR", repo.cran=TRUE)'
  only:
    - master
  artifacts:
    paths:
      - public
