language: r

env:
 global:
  - _R_CHECK_FORCE_SUGGESTS_=false

apt_packages:
 - r-cran-rjava

r_packages:
 - testthat
 - microbenchmark
 - mailR
 - shiny
 - RJDBC
 - RH2

r_github_packages:
 - Rdatatable/data.table
 - jangorecki/dwtools