language: r
sudo: required

before_install:
 - sudo service postgresql-9.1 stop
 - sudo apt-get remove --purge -y postgresql-9.1

apt_packages:
 - postgresql-9.5
 - libpq-dev

r_packages:
 - DBI
 - RPostgreSQL
 - data.table

r_github_packages:
 - olafmersmann/microbenchmarkCore

env:
 - POSTGRES_HOST="127.0.0.1" POSTGRES_DATABASE=logrdb POSTGRES_USER=logruser POSTGRES_PASSWORD=logrpass POSTGRES_PORT=5433

before_script:
 - sudo su postgres -c "psql -c \"CREATE USER logruser WITH PASSWORD 'logrpass';\""
 - sudo su postgres -c "createdb -O logruser logrdb"

after_script:
  - cat $(find . -maxdepth 1 -name "*.Rcheck" -type d)/tests/tests.Rout