language: r

apt_packages:
 - r-cran-rjava
 - r-cran-rodbc

r_packages:
 - testthat
 - microbenchmark
 - knitr
 - mailR
 - shiny
 - DBI
 - RJDBC
 - RH2

r_github_packages:
 - Rdatatable/data.table
 - jangorecki/dwtools