language: r
sudo: required

apt_packages:
 - postgresql
 - libpq-dev

r_packages:
 - DBI
 - RPostgreSQL

r_github_packages:
 - Rdatatable/data.table
 - jangorecki/microbenchmark@noggplot2
 
before_script:
 - sudo su postgres -c "psql -c \"CREATE USER logruser WITH PASSWORD 'logrpass';\""
 - sudo su postgres -c "createdb -O logruser logrdb"

after_script:
  - cat $(find . -maxdepth 1 -name "*.Rcheck" -type d)/tests/tests.Rout